set(headers
    src/Hooks.h
    src/Config/ConfigPath.h
    src/Config/Config.h
    src/Config/StyleConfig.h
    src/Config/ConfigAdapter.h
    src/Config/SpellType.h
    src/Config/Ports/HudSettings.h
    src/Config/Ports/InputBindings.h
    src/Config/Ports/PatchSettings.h
    src/Config/Ports/SlotAssignments.h
    src/Persistence/SpellSettingsDB.h
    src/Persistence/SaveSpellDB.h
    src/Persistence/Slots.h
    src/UI/HudManager.h
    src/UI/HudState.h
    src/UI/SlotDrawer.h
    src/UI/PopupDrawer.h
    src/UI/Strings.h
    src/UI/MENU.h
    src/UI/TextureManager.h
    src/UI/SlotAnimator.h
    src/UI/SlotLayout.h
    src/UI/FontLoader.h
    src/UI/HoveredForm.h
    src/UI/PolyFill.h
    src/UI/HudTextUtil.h
    src/Input/Input.h
    src/Input/EventFilter.h
    src/Input/ExclusivePending.h
    src/Input/HotkeyCache.h
    src/Input/HudToggle.h
    src/Input/InputInternal.h
    src/Input/InputState.h
    src/Input/ReplaySystem.h
    src/State/State.h
    src/State/Action.h
    src/State/AnimListener.h
    src/State/CastGuardEvents.h
    src/State/InventoryUtil.h
    src/State/SyntheticInput.h
    src/State/Assign.h
    src/State/SpellClassify.h
    src/State/EquipSink.h
    src/State/SlotCostUtil.h
    src/Adapters/Inbound/SpellTypeDetector.h
    src/Adapters/Outbound/EquipSlots.h
)