set(sources
    src/plugin.cpp
    src/Hooks.cpp
    src/Config/Config.cpp
    src/Config/StyleConfig.cpp
    src/Config/ConfigAdapter.cpp
    src/Persistence/SpellSettingsDB.cpp
    src/Persistence/SaveSpellDB.cpp
    src/Persistence/Slots.cpp
    src/UI/Strings.cpp
    src/UI/MENU.cpp
    src/UI/HudManager.cpp
    src/UI/TextureManager.cpp
    src/UI/SlotDrawer.cpp
    src/UI/PopupDrawer.cpp
    src/UI/HoveredForm.cpp
    src/Input/InputFilter.cpp
    src/Input/ExclusiveTracker.cpp
    src/Input/HotkeyMatcher.cpp
    src/Input/HudToggle.cpp
    src/Input/ReplaySystem.cpp
    src/Input/PhysicalReconciler.cpp
    src/State/Action.cpp
    src/State/AnimListener.cpp
    src/State/InventoryUtil.cpp
    src/State/SyntheticInput.cpp
    src/State/MagicStateLifecycle.cpp
    src/State/MagicStatePump.cpp
    src/State/MagicStateSlot.cpp
    src/State/Assign.cpp
    src/State/EquipSink.cpp
    src/State/SlotCostUtil.cpp
    src/Application/InputController.cpp
    src/Application/HudController.cpp
    src/Adapters/Inbound/SpellTypeDetector.cpp
    src/Detours/detours.cpp
    src/Detours/disasm.cpp
    src/Detours/disolx64.cpp
    src/Detours/image.cpp
    src/Detours/modules.cpp
)